#Ansible Jenkins Master, sample playbook - jenkins-maters-sample.yml
---
- hosts:  "{{ passed+in_hosts }}"
  become:  yes
  remote_user:  ec2-user
  become_user:  root
  tasks:
    - name:  install Git client
      yum:
        name:  git
        state:  present
